name: "✨Idea - Feature Request"
title: "✨[Idea] - <TITLE_OF_ISSUE>"
description: Share your ideas with us!
labels: [feature]
body:
- type: object
  properties:
    typ:
      type: string
      enum:
        - Component
        - Idea
    dane:
      type: object
      properties:
        - component:
          type: object
            properties:
              nazwa_komponentu:
                type: string
                description: Nazwa komponentu
        - idea:
          type: object
            properties:
              opis_idei:
                type: string
                description: Opis idei
              czy_warta_rozważenia:
                type: boolean
                description: Czy idea jest warta rozważenia?
