---
name: Custom issue template
about: Describe this issue template's purpose here.
title: ''
labels: ''
assignees: ''

---
title: Szablon zgłoszenia funkcji  # Replace with your desired title
type: object
properties:
  typ:
    type: string
    enum:
      - Component
      - Idea
 
